from enum import Enum

class States(int, Enum):
    MAIN_MENU = 0
    SELECT_CATEGORY = 1
    SELECT_FLOWER = 2
    VIEW_FLOWER = 3
    ORDER_FLOWER = 4
    ASK_NAME = 5
    ASK_ADDRESS = 6
    ASK_DELIVERY_DATE = 7
    ASK_DELIVERY_TIME = 8
    ASK_PHONE = 9
    ASK_COMMENT = 10
    CONFIRM_ORDER = 11
    ORDER_HISTORY = 12
    ORDER_STATUS = 13
    MANAGER_MENU = 14
    MANAGER_VIEW_ORDERS = 15
    MANAGER_VIEW_ORDER = 16
    MANAGER_CHANGE_STATUS = 17
    MANAGER_SELECT_STATUS = 18
