from enum import Enum

class States(int, Enum):
    MAIN_MENU = 0
    LANGUAGE_SELECT = 1
    SELECT_CATEGORY = 2
    SELECT_FLOWER = 3
    VIEW_FLOWER = 4
    ASK_NAME = 5
    ASK_PHONE = 6
    ASK_ADDRESS = 7
    ASK_DELIVERY_DATE = 8
    ASK_DELIVERY_TIME = 9
    ASK_COMMENT = 10
    CONFIRM_ORDER = 11
    ORDER_HISTORY = 12
    ORDER_STATUS = 13
    ORDER_STATUS_INPUT = 14
    MANAGER_MENU = 15
    MANAGER_VIEW_ORDERS = 16
    MANAGER_VIEW_ORDER = 17
    MANAGER_CHANGE_STATUS = 18
